export const GET_TEAMS = "GET_TEAMS";

export const CHANGE_PLAYER = "CHANGE_PLAYER";
export const GET_PLAYERS = "GET_PLAYERS";
export const SET_HOME_PLAYERS = "SET_HOME_PLAYERS";
export const SET_AWAY_PLAYERS = "SET_AWAY_PLAYERS";
export const CHANGE_PLAYERS_ON_FIELD = "CHANGE_PLAYERS_ON_FIELD";
export const CHANGE_PLAYER_POSITION = "CHANGE_PLAYER_POSITION";

export const CHANGE_QUARTER = "CHANGE_QUARTER";
export const CHANGE_YARD = "CHANGE_YARD";
export const CHANGE_DOWN = "CHANGE_DOWN";
export const CHANGE_HOME = "CHANGE_HOME";
export const CHANGE_AWAY = "CHANGE_AWAY";
export const CHANGE_TEMPERATURE = "CHANGE_TEMPERATURE";
export const CHANGE_WEATHER_CONDITION = "CHANGE_WEATHER_CONDITION";
export const CHANGE_LOADING_STATUS = "CHANGE_LOADING_STATUS";
export const CHANGE_SEASON = "CHANGE_SEASON";
export const CHANGE_SEASON_LOADING_STATUS = "CHANGE_SEASON_LOADING_STATUS";
export const CHANGE_RUSHER_DIRECTION = "CHANGE_RUSHER_DIRECTION";
export const CHANGE_BALL_POSITION = "CHANGE_BALL_POSITION";
